In [2]:
import numpy as np

In [3]:
X = np.load('x_data.npy')
X.shape

(35067, 26, 25)

In [4]:
X[0,:,:]

array([[8.66779476e-04, 1.66673008e-03, 1.66670111e-03, 1.66667339e-03,
        1.66668818e-03, 1.66668307e-03, 1.66673728e-03, 1.66671887e-03,
        1.66658475e-03, 1.66658977e-03, 1.66665478e-03, 1.66664744e-03,
        1.66670703e-03, 1.66670798e-03, 1.66673976e-03, 1.66669072e-03,
        1.66667549e-03, 1.66667697e-03, 1.66663250e-03, 1.66661057e-03,
        1.66656836e-03, 1.66660252e-03, 1.66661330e-03, 1.66656539e-03,
        8.00021220e-04],
       [6.95203341e-04, 8.33364225e-04, 8.33351832e-04, 8.33334933e-04,
        8.33345695e-04, 8.33334568e-04, 8.33379264e-04, 8.33369311e-04,
        8.33291671e-04, 8.33296508e-04, 8.33330986e-04, 8.33317040e-04,
        8.33372664e-04, 8.33348792e-04, 8.33359999e-04, 8.33352483e-04,
        8.33342412e-04, 8.33337325e-04, 8.33311731e-04, 8.33307242e-04,
        8.33290813e-04, 8.33302590e-04, 8.33304948e-04, 8.33283752e-04,
        6.53953815e-04],
       [3.53853864e-04, 4.42270918e-09, 6.29369590e-09, 9.95406769e-09,
        1.3574

In [5]:
Y = np.load('y_data.npy')
Y.shape

(35067, 5)

In [6]:
X = X.reshape(-1,26, 25,1)

In [7]:
Y[50:100]

array([[0.        , 0.        , 0.56639453, 0.        , 0.        ],
       [0.        , 0.        , 0.5639491 , 0.        , 0.        ],
       [0.        , 0.        , 0.56150498, 0.        , 0.        ],
       [0.        , 0.        , 0.55906224, 0.        , 0.        ],
       [0.        , 0.        , 0.55662095, 0.        , 0.        ],
       [0.        , 0.        , 0.55418119, 0.        , 0.        ],
       [0.        , 0.        , 0.55174303, 0.        , 0.        ],
       [0.        , 0.        , 0.54930655, 0.        , 0.        ],
       [0.        , 0.        , 0.5468718 , 0.        , 0.        ],
       [0.        , 0.        , 0.54443888, 0.        , 0.        ],
       [0.        , 0.        , 0.54200785, 0.        , 0.        ],
       [0.        , 0.        , 0.53957878, 0.        , 0.        ],
       [0.        , 0.        , 0.53715175, 0.        , 0.        ],
       [0.        , 0.        , 0.53472681, 0.        , 0.        ],
       [0.        , 0.        , 0.

In [8]:
from sklearn.model_selection import train_test_split

In [9]:
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, shuffle = False)

In [10]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import tensorflow as tf
from keras.layers import Dense, Conv2D, Flatten, MaxPool2D
from tensorflow.keras.models import Sequential


In [11]:
#defining model
model=Sequential()
#adding convolution layer
model.add(Conv2D(32,(3,3),activation='relu',input_shape=(26,25,1)))
#adding pooling layer
model.add(MaxPool2D(2,2))
#adding fully connected layer
model.add(Flatten())
model.add(Dense(200,activation='relu'))
model.add(Dense(100,activation='relu'))
#adding output layer
model.add(Dense(5,activation='sigmoid'))

print(model.summary())

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d (Conv2D)              (None, 24, 23, 32)        320       
_________________________________________________________________
max_pooling2d (MaxPooling2D) (None, 12, 11, 32)        0         
_________________________________________________________________
flatten (Flatten)            (None, 4224)              0         
_________________________________________________________________
dense (Dense)                (None, 200)               845000    
_________________________________________________________________
dense_1 (Dense)              (None, 100)               20100     
_________________________________________________________________
dense_2 (Dense)              (None, 5)                 505       
Total params: 865,925
Trainable params: 865,925
Non-trainable params: 0
__________________________________________________

In [12]:
epochs = 10

model.compile(loss="Poisson", optimizer="adam", metrics=["accuracy"])

In [13]:
model.fit(x_train, y_train, epochs=epochs)

Epoch 1/10
877/877 [==============================] - 10s 3ms/step - loss: 0.2731 - accuracy: 0.6391
Epoch 2/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2687 - accuracy: 0.6421
Epoch 3/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2684 - accuracy: 0.6421
Epoch 4/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2683 - accuracy: 0.6421
Epoch 5/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2682 - accuracy: 0.6421
Epoch 6/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2680 - accuracy: 0.6421
Epoch 7/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2682 - accuracy: 0.6421
Epoch 8/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2682 - accuracy: 0.6421
Epoch 9/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2681 - accuracy: 0.6421
Epoch 10/10
877/877 [==============================] - 3s 3ms/step - loss: 0.2680 - accuracy: 0.642

In [14]:
score = model.evaluate(x_test, y_test, verbose=0)

print(score[0])
print(score[1])


0.2596040368080139
0.654262900352478


In [15]:
tem = model.predict(x_train[1000:1010])
tem

array([[0.04232579, 0.04340893, 0.04762348, 0.05012207, 0.23982103],
       [0.04222504, 0.04329436, 0.04751706, 0.05000546, 0.2396645 ],
       [0.04215416, 0.04322435, 0.04745135, 0.04992843, 0.23952551],
       [0.04225115, 0.04333951, 0.04757431, 0.05005476, 0.23974732],
       [0.04237833, 0.04345277, 0.04769642, 0.05018228, 0.23989286],
       [0.04232579, 0.04340893, 0.04762348, 0.05012207, 0.23982103],
       [0.04221983, 0.04329576, 0.04751127, 0.05000238, 0.23966682],
       [0.042156  , 0.04322699, 0.04745185, 0.04993173, 0.2395245 ],
       [0.04224835, 0.04333708, 0.04757183, 0.05005113, 0.23974706],
       [0.04237194, 0.04344488, 0.04769334, 0.05017357, 0.23989703]],
      dtype=float32)

In [16]:
y_train[1000:1010]

array([[0.        , 0.        , 0.        , 0.        , 0.84926336],
       [0.        , 0.        , 0.        , 0.        , 0.84643894],
       [0.        , 0.        , 0.        , 0.        , 0.84359509],
       [0.        , 0.        , 0.        , 0.        , 0.84073207],
       [0.        , 0.        , 0.        , 0.        , 0.83785013],
       [0.        , 0.        , 0.        , 0.        , 0.83494955],
       [0.        , 0.        , 0.        , 0.        , 0.83203059],
       [0.        , 0.        , 0.        , 0.        , 0.82909349],
       [0.        , 0.        , 0.        , 0.        , 0.82613854],
       [0.        , 0.        , 0.        , 0.        , 0.823166  ]])